### ISSUE TITLE
nginx binary: ELFCLASS64

### ISSUE THREAD

**Issue by DevEddy** [EasySmartHome/CloudMatic-CCUAddon#10]
Seit RaspberryMatic 3.69.7.20230626 scheint die `nginx` binary nicht mehr zu funktionieren.

```
root@homematic-raspi:/opt/mh/user# ./nginx -v
./nginx: error while loading shared libraries: libpcre.so.1: wrong ELF class: ELFCLASS64
```

@jens-maus das letzte Mal hattest du die binary aktualisiert. Muss dieses Mal wieder die nginx binary aktualisiert werden? Hast du diese?

**Comment by jens-maus** [comment]
Bitte genau spezifizieren auf welchem Host du probierst das nginx binary bzw. das Addon zu nutzen. Was ist die Host Hardware?

**Comment by DevEddy** [comment]
Ist hier die Information bei die du brauchst?

```
root@homematic-raspi:~# cat /proc/cpuinfo
[...]
Hardware    : BCM2835
Revision    : a02082
Model       : Raspberry Pi 3 Model B Rev 1.2
```

```
root@homematic-raspi:~# uname -a
Linux homematic-raspi 6.1.21 #1 SMP PREEMPT Mon Jun 26 07:35:37 UTC 2023 aarch64 GNU/Linux
```

```
root@homematic-raspi:~# cat /etc/os-release
NAME=Buildroot
VERSION=-g478749d
ID=buildroot
VERSION_ID=2023.05
PRETTY_NAME="Buildroot 2023.05"
```

**Comment by jens-maus** [comment]
Konnte das Problem nachvollziehen. Hier fehlte in neueren RaspberryMatic versionen in der noch existenten 32bit multilib Umgebung die `libpcre.so.1` library. Diese existierte nur als 64bit binary. Allerdings ist das nginx das mit dem CloudMatic Addon mitkommt leider immer noch 32bit only. Vielleicht sollte man hier einmal darüber nachdenken die beiden binaries (`nginx` und `zabbix_agent`) die noch 32bit sind und dem Addon beiliegen als 64bit binaries mit anzubieten und diese dann stattdessen zu verwenden als die vorkompilierten 32bit versionen die man hier einfach nur stumpf im Addon mitliefert und früher oder später schon wegen glibc Anpassungen in der Zukunft wohl irgendwann nicht mehr lauffähig sein werden.

**Comment by DevEddy** [comment]
Danke für die schnelle Prüfung und Behebung des Problems! Ich habe deine Anmerkung bezüglich 64bit `nginx` zur Umsetzung aufgenommen.

**Comment by DevEddy** [comment]
Ist mit der Version [3.71.12.20230826](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.71.12.20230826) gefixt.
