### ISSUE TITLE
CloudMatic auf RaspberryMatic Teil:1 - erstmalige Aktivierung von CloudMatic (Testmonat) nicht möglich

### ISSUE THREAD

**Issue by Baxxy13** [EasySmartHome/CloudMatic-CCUAddon#11]
Hallo CloudMatic-Team,
ich wollte heute auf einem RaspberryMatic - Testsystem den kostenlosen Probemonat mit CloudMatic-Connect ausprobieren.
Dabei sind mir einige (negative) Dinge aufgefallen die ich hier mal schildern werde.

Zum Testsystem:
RaspberryMatic 3.71.12.20230826 als x86 Virtuelle Maschine auf einem Proxmox

Ablauf:
1. Über den CloudMatic-Button in der Systemsteuerung CloudMatic aufgerufen und mich mit frischen Nutzerdaten registriert.
2. Anschließend erschien dieses Fenster welches auch nach 10Min nicht verschwand.
![CM_1_ewige_Registrierung](https://github.com/EasySmartHome/CloudMatic-CCUAddon/assets/54898249/c16ab1fe-ea46-41e2-86fb-d9a28f498415)
3. Genug gewartet und oben auf "Start" geklickt, was mich dann zu folgender Seite führte:
![CM_2_ewige_Aktivierung](https://github.com/EasySmartHome/CloudMatic-CCUAddon/assets/54898249/eedc817e-6ef8-4a53-b904-a2b5d13597a6)
4. Die 15Min habe ich abgewartet und zwischendurch ab und zu "Seite neu laden" angeklickt, ohne Ergebnis.
Nebenbei habe ich meine RaspberryMatic beobachtet und dabei folgendes im Logfile gefunden:
```
Oct  4 17:36:23 RM-Test-VM-96 user.info homematic: VPN Dienst wird aktiviert
Oct  4 17:36:23 RM-Test-VM-96 user.info homematic: meine-homematic.de Initialer Konfigurations - Transfer gestartet
Oct  4 17:36:23 RM-Test-VM-96 user.info homematic: meine-homematic.de Update Prozess aktualisiert Dateirechte
Oct  4 17:37:23 RM-Test-VM-96 user.info homematic: meine-homematic.de Initialer Konfigurations - Transfer gestartet
Oct  4 17:37:24 RM-Test-VM-96 user.info homematic: meine-homematic.de Update Prozess aktualisiert Dateirechte
Oct  4 17:38:24 RM-Test-VM-96 user.info homematic: meine-homematic.de Initialer Konfigurations - Transfer gestartet
Oct  4 17:38:24 RM-Test-VM-96 user.info homematic: meine-homematic.de Update Prozess aktualisiert Dateirechte
.
.
.
Oct  4 18:07:33 RM-Test-VM-96 user.info homematic: meine-homematic.de Initialer Konfigurations - Transfer gestartet
Oct  4 18:07:33 RM-Test-VM-96 user.info homematic: meine-homematic.de Update Prozess aktualisiert Dateirechte
Oct  4 18:08:33 RM-Test-VM-96 user.info homematic: meine-homematic.de Initialer Konfigurations - Transfer gestartet
Oct  4 18:08:33 RM-Test-VM-96 user.info homematic: meine-homematic.de Update Prozess aktualisiert Dateirechte
```
  (Log gekürzt, das läuft jetzt, zum Zeitpunkt des Schreibens, immer noch so)

5. Gut, wenn hier was hakelt soll man ja auf den Link klicken...
![CM_3_kaputter_Link](https://github.com/EasySmartHome/CloudMatic-CCUAddon/assets/54898249/9be9b0b4-7267-49db-a962-b04a2ca630b9)
6. ...der aber leider ins Nirgendwo führt.
![CM_4_kaputter_Link_aufgerufen](https://github.com/EasySmartHome/CloudMatic-CCUAddon/assets/54898249/d543d3cc-37b1-4eda-a444-66a75ba63959)

Zusammenfassung:
Einfach mal schnell den CloudMatic Testzugang zu aktivieren war mir, bis hierher, nicht möglich.
Es wäre schön wenn ihr euren "Aktivierungs-Flow" selbst mal testen und ggf. verbessern könntet.

Ob hier tatsächlich ein Bug vorliegt, und wenn ja, ob er RaspberryMatic oder CloudMatic zuzuordnen ist, kann ich nicht abschließend sagen.

**Comment by DevEddy** [comment]
Hey @Baxxy13, Danke für Deine Meldung. Den fehlerhaften Link haben wir korrigiert.

Bezüglich der automatischen Verknüpfung ist es so, dass diese über die Seriennummer der Zentrale stattfindet. Wenn es keine gibt, funktioniert dieser Prozess nicht. Dies ist z.B. bei RaspberryMatic unter Proxmox der Fall.

**Comment by Baxxy13** [comment]
> dass diese über die Seriennummer der Zentrale stattfindet.

Verstehe, ihr nutzt die Serial des BCM vom Raspi. 
Die gibt es natürlich in virtuellen Maschinen sowie in Docker-Containern (auf x86) nicht. 

Würde es Sinn machen für solche Systeme (bei der erstmaligen Inbetriebnahme) eine random Serial zu erzeugen die ihr auslesen könntet? Diese könnte dann im /userfs abgelegt werden damit sie auch im Backup enthalten ist.
Sollte ja nicht so schwer umzusetzen sein.

**Comment by jens-maus** [comment]
Besser wäre ggf. einfach die MAC Adresse des eth0 Interface als pseudo serialnumber zu verwenden.

**Comment by Baxxy13** [comment]
Die MAC wird ausgelesen, aber als BidCoS-Address in der `/etc/config/addons/mh/ids` abgelegt. 
Die eigentliche Serial bleibt leer.
Bei einer CCU2 hingegen wird die MAC als SerialNumber verwendet.
