### ISSUE TITLE
CloudMatic auf RaspberryMatic Teil:2 - einspielen des heruntergeladenen persönlichen Schlüssels fehlerhaft

### ISSUE THREAD

**Issue by Baxxy13** [EasySmartHome/CloudMatic-CCUAddon#12]
Nachdem ich in #11 nicht weiterkam loggte ich mich im Kundenbereich ein und lud den Lizensschlüssel direkt herunter.
![CM_5_download_Key](https://github.com/EasySmartHome/CloudMatic-CCUAddon/assets/54898249/c78867e0-5dd9-4933-8b2b-137d5b72f134)

Anschließend der Upload auf die RaspberryMatic... 
![CM_6_upload_Key](https://github.com/EasySmartHome/CloudMatic-CCUAddon/assets/54898249/9a1b1f46-a716-4263-b253-625e1c548be6)
... welcher dann auch gleich einen Error wirft.
![CM_7_upload_Key_Error](https://github.com/EasySmartHome/CloudMatic-CCUAddon/assets/54898249/8d212688-bb45-4bfc-a4ad-d8d66c719418)

Die RaspberryMatic hat den Key aber wohl übernommen, auch wenn die Meldungen im Log etwas suspekt aussehen.
```
Oct  4 18:32:43 RM-Test-VM-96 kern.err kernel: [ 4640.490564] /dev/sda3: Can't open blockdev
Oct  4 18:32:43 RM-Test-VM-96 kern.err kernel: [ 4640.490900] /dev/sda3: Can't open blockdev
Oct  4 18:32:43 RM-Test-VM-96 kern.info kernel: [ 4640.514799] EXT4-fs (sda2): re-mounted. Quota mode: none.
Oct  4 18:32:43 RM-Test-VM-96 kern.info kernel: [ 4640.537967] EXT4-fs (sda2): re-mounted. Quota mode: none.
Oct  4 18:33:41 RM-Test-VM-96 user.info homematic: cloudmatic.de loophammer startet openvpn.
```

Zumindest mein Testzugang ist nun aktiv und funktioniert.

Zusammenfassung:
Da #11 schon so holprig lief wäre es gut wenn zumindest das lokale Einspielen des Key's fehlerfrei abliefe.
Es funktionierte zwar letztendlich, sorgt aber doch für Verwirrung wenn Fehler aufpoppen.

**Comment by DevEddy** [comment]
Hey @Baxxy13, Danke nochmal an das Feedback. Dieses Problem scheint nur auf RaspberryMatic Systeme zu passieren, das Archiv lässt sich auf jeder normalen CCU ohne Fehlermeldung installieren. Ggf. weiß @jens-maus woran das liegen kann?

**Comment by jens-maus** [comment]
Das wird an der etwas anderen Verarbeitung des `update_script` Scriptes liegen. Bei RaspberryMatic kann man via anderen exit Codes dieses Scriptes ja steuern ob dem Nutzer angezeigt wird das eon Reboot notwendig ist oder nicht. Bei der CCU Firmware findet diese Unterscheidung nicht statt. Ergo, das update_Script muss/sollte leicht angepasst werden und hier sichergestellt werden das zumindest ein exit Code von 0 zurückgegeben wird. Als Beispiel siehe hier:

https://github.com/homematic-community/hm_pdetect/blob/master/addon/update_script#L77

**Comment by DevEddy** [comment]
Wir haben das `update_script` angepasst und geben den Code `10` für einen Reboot zurück. Nach meinem Tests sieht jetzt alles gut aus. Wichtig ist nur, dass nur die neu generierten Schlüssel diese Änderung erhalten.

**Comment by jens-maus** [comment]
Braucht das denn wirklich einen reboot? Bitte macht es doch lieber so das ihr OpenVPN innerhalb des update scripted neustarten mit dem neuen keys und vermeidet einen kompletten Neustart bzw die Notifizierung das der Nutzer diesen machen soll. Alle Addons tun ja mehr oder weniger das selbe und sollten als best practice das erzwingen eines Neustarts soweit es geht vermeiden.
