### ISSUE TITLE
Please add some user authentication addon usage or disable sensitive spots

### ISSUE THREAD

**Issue by psytester** [EasySmartHome/CloudMatic-CCUAddon#8]
The Homematic Addon is accessible without any user session authentication.
If this VPN access has been set up, but port forwarding has been set up in the router as well to the CCU (Arggh!!!), the CGI scripts are executable for everyone.

In case of ```http://IP_of_CCU/addons/mh/dotest2.cgi``` shows up an user account
```
.....
Inhalt mhcfg
    userkennung= ..... here not "none" .....
......
```

The Denial of Service could be:
* VPN setup is deleted by ```http://IP_of_CCU/addons/mh/cleanup.cgi```
afterwards ```http://IP_of_CCU/addons/mh/dotest2.cgi``` shows
```
.....
Inhalt mhcfg
    userkennung=none
......
```

* shutting down the VPN service by ```http://IP_of_CCU/addons/mh/dienstaus.cgi```
* shutting down the Reverse proxy by ```http://IP_of_CCU/addons/mh/dienstausngx.cgi```
* shutting down the CloudMatic monitoring by ```http://IP_of_CCU/addons/mh/dienstauszbx.cgi```

**Comment by m-scheffler** [comment]
We created a quick fix by not allowing public IPs requesting this files now. Unfortunately we have to wait until the upstream will pull the fixes an integrate them into the firmware.

Thanks!

**Comment by jens-maus** [comment]
@m-scheffler Upstream is listening ;-)

However, please note that your changes by simply introducing REMOTE_ADDR checking will not work for IPv6 enabled installations. Thus, a user authentication is IMHO still required and should not be too complicated to implement.

**Comment by m-scheffler** [comment]
@jens-maus we're aware of that, and as I wrote this is only a "quick fix" ;)
